name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        services:
            postgres:
                image: postgres:15
                ports:
                    - 5432:5432
                env:
                    POSTGRES_DB: settlement
                    POSTGRES_USER: settlement_user
                    POSTGRES_PASSWORD: settlement_pass
                options: >-
                    --health-cmd "pg_isready -U settlement_user" --health-interval 10s --health-timeout 5s --health-retries 5
            zookeeper:
                image: confluentinc/cp-zookeeper:7.5.0
                ports:
                    - 22181:2181
                env:
                    ZOOKEEPER_CLIENT_PORT: 2181
                    ZOOKEEPER_TICK_TIME: 2000
            kafka:
                image: confluentinc/cp-kafka:7.5.0
                ports:
                    - 9092:9092
                env:
                    KAFKA_BROKER_ID: 1
                    KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
                    KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
                    KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9092
                    KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
                    KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
                options: >-
                    --health-cmd "cub kafka-ready -b localhost:9092 1 20" --health-interval 10s --health-timeout 10s --health-retries 10
        steps:
            - uses: actions/checkout@v4
            - name: Set up JDK 24
              uses: actions/setup-java@v4
              with:
                  distribution: temurin
                  java-version: "24"
                  cache: maven
            - name: Build and Test
              env:
                  DB_URL: jdbc:postgresql://localhost:5432/settlement
                  DB_USER: settlement_user
                  DB_PASSWORD: settlement_pass
                  KAFKA_BOOTSTRAP_SERVERS: localhost:9092
              run: mvn -B clean verify
            - name: Spotless Check
              run: mvn -B spotless:check
